# Site settings
title: "A Frightful Number!"
email: jamie@performantsoftware.com
description: "Mapping Daniel Defoe’s _A Journal of the Plague Year_"
url: "https://a-frightful-number.netlify.app"
twitter_username: performantsoft
github_username:  performant-software

# Where things are
destination:      ./_site
# source:           ./_source


# Handling Reading
exclude:          ["templates", "Gemfile", "Gemfile.lock", "README.md", ".gitignore"]

# Conversion
markdown: kramdown

# Compensating for gh-pages project site

# https://github.com/jekyll/jekyll/issues/332

# asset_url: https://itinerary-maps.netlify.app/design-framework
